drop database if exists exo_contacts;
create database exo_contacts;

use exo_contacts;

create table pays(
    iso_3 char(3) primary key,
    nom varchar(70),
    iso_2 varchar(3),
    nationalite varchar(50)
);

create table contacts(
    id int primary key auto_increment,
    nom varchar(70),
    pays varchar(70),
    date_de_naissance DATE,
    sexe varchar(10),
    adresse text,
    cp varchar(10),
    ville varchar(70),
    pays_iso_3 char(3),
    foreign key (pays_iso_3) references pays(iso_3)
);



insert into pays(iso_2, iso_3, nom, nationalite) values
('AF', 'AFG', 'Afghanistan', 'Afghane'),
('AL', 'ALB', 'Albanie', 'Albanaise'),
('DZ', 'DZA', 'Algerie', 'Algerienne'),
('AD', 'AND', 'Andorre', 'Andorrane'),
('AO', 'AGO', 'Angola', 'Angolaise'),
('AG', 'ATG', 'Antigua-et-Barbuda', 'Antiguaise'),
('AR', 'ARG', 'Argentine', 'Argentine'),
('AM', 'ARM', 'Armenie', 'Armenienne'),
('AU', 'AUS', 'Australie', 'Australienne'),
('AT', 'AUT', 'Autriche', 'Autrichienne'),
('AZ', 'AZE', 'Azerbaidjan', 'Azerbaidjanaise'),
('BS', 'BHS', 'Bahamas', 'Bahameenne'),
('BH', 'BHR', 'Bahrein', 'Bahreinienne'),
('BD', 'BGD', 'Bangladesh', 'Bangladaise'),
('BB', 'BRB', 'Barbade', 'Barbadienne'),
('BY', 'BLR', 'Bielorussie', 'Bielorusse'),
('BE', 'BEL', 'Belgique', 'Belge'),
('BZ', 'BLZ', 'Belize', 'Belizienne'),
('BJ', 'BEN', 'Benin', 'Beninoise'),
('BT', 'BTN', 'Bhoutan', 'Bhoutanaise'),
('BO', 'BOL', 'Bolivie', 'Bolivienne'),
('BA', 'BIH', 'Bosnie-Herzegovine', 'Bosnienne'),
('BR', 'BRA', 'Bresil', 'Bresilienne'),
('BN', 'BRN', 'Brunei Darussalam', 'Bruneienne'),
('BG', 'BGR', 'Bulgarie', 'Bulgare'),
('BF', 'BFA', 'Burkina Faso', 'Burkinabee'),
('BI', 'BDI', 'Burundi', 'Burundaise'),
('CV', 'CPV', 'Cap-Vert', 'Cap-verdienne'),
('KH', 'KHM', 'Cambodge', 'Cambodgienne'),
('CM', 'CMR', 'Cameroun', 'Camerounaise'),
('CA', 'CAN', 'Canada', 'Canadienne'),
('CF', 'CAF', 'Republique centrafricaine', 'Centrafricaine'),
('TD', 'TCD', 'Tchad', 'Tchadienne'),
('CL', 'CHL', 'Chili', 'Chilienne'),
('CN', 'CHN', 'Chine', 'Chinoise'),
('CO', 'COL', 'Colombie', 'Colombienne'),
('KM', 'COM', 'Comores', 'Comorienne'),
('CG', 'COG', 'Congo', 'Congolaise'),
('CR', 'CRI', 'Costa Rica', 'Costaricaine'),
('HR', 'HRV', 'Croatie', 'Croate'),
('CU', 'CUB', 'Cuba', 'Cubaine'),
('CY', 'CYP', 'Chypre', 'Chypriote'),
('CZ', 'CZE', 'Republique tchèque', 'Tchèque'),
('DK', 'DNK', 'Danemark', 'Danoise'),
('DJ', 'DJI', 'Djibouti', 'Djiboutienne'),
('DM', 'DMA', 'Dominique', 'Dominiquaise'),
('DO', 'DOM', 'Republique dominicaine', 'Dominicaine'),
('EC', 'ECU', 'Equateur', 'Equatorienne'),
('EG', 'EGY', 'Egypte', 'Egyptienne'),
('SV', 'SLV', 'El Salvador', 'Salvadorienne'),
('GQ', 'GNQ', 'Guinee equatoriale', 'Equato-guineenne'),
('ER', 'ERI', 'Erythree', 'Erythreenne'),
('EE', 'EST', 'Estonie', 'Estonienne'),
('SZ', 'SWZ', 'Eswatini', 'Eswatinienne'),
('ET', 'ETH', 'ethiopie', 'Ethiopienne'),
('FJ', 'FJI', 'Fidji', 'Fidjienne'),
('FI', 'FIN', 'Finlande', 'Finlandaise'),
('FR', 'FRA', 'France', 'Française'),
('GA', 'GAB', 'Gabon', 'Gabonaise'),
('GM', 'GMB', 'Gambie', 'Gambienne'),
('GE', 'GEO', 'Georgie', 'Georgienne'),
('DE', 'DEU', 'Allemagne', 'Allemande'),
('GH', 'GHA', 'Ghana', 'Ghaneenne'),
('GR', 'GRC', 'Grèce', 'Grecque'),
('GD', 'GRD', 'Grenade', 'Grenadienne'),
('GT', 'GTM', 'Guatemala', 'Guatemaltèque'),
('GN', 'GIN', 'Guinee', 'Guineenne'),
('GW', 'GNB', 'Guinee-Bissau', 'Bissau-Guineenne'),
('GY', 'GUY', 'Guyana', 'Guyanaise'),
('HT', 'HTI', 'Haiti', 'Haitienne'),
('HN', 'HND', 'Honduras', 'Hondurienne'),
('HU', 'HUN', 'Hongrie', 'Hongroise'),
('IS', 'ISL', 'Islande', 'Islandaise'),
('IN', 'IND', 'Inde', 'Indienne'),
('ID', 'IDN', 'Indonesie', 'Indonesienne'),
('IR', 'IRN', 'Iran', 'Iranienne'),
('IQ', 'IRQ', 'Irak', 'Irakienne'),
('IE', 'IRL', 'Irlande', 'Irlandaise'),
('IL', 'ISR', 'Israel', 'Israelienne'),
('IT', 'ITA', 'Italie', 'Italienne'),
('JM', 'JAM', 'Jamaique', 'Jamaicaine'),
('JP', 'JPN', 'Japon', 'Japonaise'),
('JO', 'JOR', 'Jordanie', 'Jordanienne'),
('KZ', 'KAZ', 'Kazakhstan', 'Kazakhe'),
('KE', 'KEN', 'Kenya', 'Kenyane'),
('KI', 'KIR', 'Kiribati', 'Kiribatienne'),
('KP', 'PRK', 'Coree du Nord', 'Nord-coreenne'),
('KR', 'KOR', 'Coree du Sud', 'Sud-coreenne'),
('KW', 'KWT', 'Koweit', 'Koweitienne'),
('KG', 'KGZ', 'Kirghizistan', 'Kirghize'),
('LA', 'LAO', 'Laos', 'Laotienne'),
('LV', 'LVA', 'Lettonie', 'Lettone'),
('LB', 'LBN', 'Liban', 'Libanaise'),
('LS', 'LSO', 'Lesotho', 'Lesothienne'),
('LR', 'LBR', 'Liberia', 'Liberienne'),
('LY', 'LBY', 'Libye', 'Libyenne'),
('LI', 'LIE', 'Liechtenstein', 'Liechtensteinoise'),
('LT', 'LTU', 'Lituanie', 'Lituanienne'),
('LU', 'LUX', 'Luxembourg', 'Luxembourgeoise'),
('MK', 'MKD', 'Macedoine du Nord', 'Macedonienne'),
('MG', 'MDG', 'Madagascar', 'Malgache'),
('MW', 'MWI', 'Malawi', 'Malawite'),
('MY', 'MYS', 'Malaisie', 'Malaisienne'),
('MV', 'MDV', 'Maldives', 'Maldivienne'),
('ML', 'MLI', 'Mali', 'Malienne'),
('MT', 'MLT', 'Malte', 'Maltaise'),
('MH', 'MHL', 'Iles Marshall', 'Marshallaise'),
('MR', 'MRT', 'Mauritanie', 'Mauritanienne'),
('MU', 'MUS', 'Maurice', 'Mauricienne'),
('MX', 'MEX', 'Mexique', 'Mexicaine'),
('FM', 'FSM', 'Micronesie', 'Micronesienne'),
('MD', 'MDA', 'Moldavie', 'Moldave'),
('MC', 'MCO', 'Monaco', 'Monegasque'),
('MN', 'MNG', 'Mongolie', 'Mongole'),
('ME', 'MNE', 'Montenegro', 'Montenegrine'),
('MA', 'MAR', 'Maroc', 'Marocaine'),
('MZ', 'MOZ', 'Mozambique', 'Mozambicaine'),
('MM', 'MMR', 'Myanmar', 'Myanmaraise'),
('NA', 'NAM', 'Namibie', 'Namibienne'),
('NR', 'NRU', 'Nauru', 'Nauruane'),
('NP', 'NPL', 'Nepal', 'Nepalaise'),
('NL', 'NLD', 'Pays-Bas', 'Neerlandaise'),
('NZ', 'NZL', 'Nouvelle-Zelande', 'Neo-Zelandaise'),
('NI', 'NIC', 'Nicaragua', 'Nicaraguayenne'),
('NE', 'NER', 'Niger', 'Nigerienne'),
('NG', 'NGA', 'Nigeria', 'Nigeriane'),
('NO', 'NOR', 'Norvège', 'Norvegienne'),
('OM', 'OMN', 'Oman', 'Omanaise'),
('PK', 'PAK', 'Pakistan', 'Pakistanaise'),
('PW', 'PLW', 'Palaos', 'Palaosienne'),
('PA', 'PAN', 'Panama', 'Panameenne'),
('PG', 'PNG', 'Papouasie-Nouvelle-Guinee', 'Papouasienne'),
('PY', 'PRY', 'Paraguay', 'Paraguayenne'),
('PE', 'PER', 'Perou', 'Peruvienne'),
('PH', 'PHL', 'Philippines', 'Philippine'),
('PL', 'POL', 'Pologne', 'Polonaise'),
('PT', 'PRT', 'Portugal', 'Portugaise'),
('QA', 'QAT', 'Qatar', 'Qatarienne'),
('RO', 'ROU', 'Roumanie', 'Roumaine'),
('RU', 'RUS', 'Russie', 'Russe'),
('RW', 'RWA', 'Rwanda', 'Rwandaise'),
('KN', 'KNA', 'Saint-Christophe-et-Nieves', 'Saint-Kittsienne-et-Nevicienne'),
('LC', 'LCA', 'Sainte-Lucie', 'Saint-Lucienne'),
('VC', 'VCT', 'Saint-Vincent-et-les-Grenadines', 'Saint-Vincentaise-et-Grenadine'),
('WS', 'WSM', 'Samoa', 'Samoane'),
('SM', 'SMR', 'Saint-Marin', 'Saint-Marinaise'),
('ST', 'STP', 'Sao Tome-et-Principe', 'Santomeenne-et-Princienne'),
('SA', 'SAU', 'Arabie saoudite', 'Saoudienne'),
('SN', 'SEN', 'Senegal', 'Senegalaise'),
('RS', 'SRB', 'Serbie', 'Serbe'),
('SC', 'SYC', 'Seychelles', 'Seychelloise'),
('SL', 'SLE', 'Sierra Leone', 'Sierra-Leonaise'),
('SG', 'SGP', 'Singapour', 'Singapourienne'),
('SK', 'SVK', 'Slovaquie', 'Slovaque'),
('SI', 'SVN', 'Slovenie', 'Slovène'),
('SB', 'SLB', 'Iles Salomon', 'Salomonaise'),
('SO', 'SOM', 'Somalie', 'Somalienne'),
('ZA', 'ZAF', 'Afrique du Sud', 'Sud-Africaine'),
('SS', 'SSD', 'Soudan du Sud', 'Soudanaise du Sud'),
('ES', 'ESP', 'Espagne', 'Espagnole'),
('LK', 'LKA', 'Sri Lanka', 'Sri-Lankaise'),
('SD', 'SDN', 'Soudan', 'Soudanaise'),
('SR', 'SUR', 'Suriname', 'Surinamaise'),
('SE', 'SWE', 'Suede', 'Suedoise'),
('CH', 'CHE', 'Suisse', 'Suisse'),
('SY', 'SYR', 'Syrie', 'Syrienne'),
('TJ', 'TJK', 'Tadjikistan', 'Tadjike'),
('TZ', 'TZA', 'Tanzanie', 'Tanzanienne'),
('TH', 'THA', 'Thailande','Thailandaise'),
('TL', 'TLS', 'Timor oriental', 'Est-timoraise'),
('TG', 'TGO', 'Togo', 'Togolaise'),
('TO', 'TON', 'Tonga', 'Tongienne'),
('TT', 'TTO', 'Trinite-et-Tobago', 'Trinidadienne-et-Tobagonienne'),
('TN', 'TUN', 'Tunisie', 'Tunisienne'),
('TR', 'TUR', 'Turquie', 'Turque'),
('TM', 'TKM', 'Turkmenistan', 'Turkmene'),
('TV', 'TUV', 'Tuvalu', 'Tuvaluane'),
('UG', 'UGA', 'Ouganda', 'Ougandaise'),
('UA', 'UKR', 'Ukraine', 'Ukrainienne'),
('AE', 'ARE', 'Emirats arabes unis', 'emirienne'),
('GB', 'GBR', 'Royaume-Uni', 'Britannique'),
('US', 'USA', 'etats-Unis', 'Americaine'),
('UY', 'URY', 'Uruguay', 'Uruguayenne'),
('UZ', 'UZB', 'Ouzbekistan', 'Ouzbèke'),
('VU', 'VUT', 'Vanuatu', 'Vanuatuane'),
('VA', 'VAT', 'Vatican', 'Vaticane'),
('VE', 'VEN', 'Venezuela', 'Venezuelienne'),
('VN', 'VNM', 'Vietnam', 'Vietnamienne'),
('YE', 'YEM', 'Yemen', 'Yemenite'),
('ZM', 'ZMB', 'Zambie', 'Zambienne'),
('ZW', 'ZWE', 'Zimbabwe', 'Zimbabweenne');


create table telephone(

    id int primary key auto_increment,
    id_contact INT(250),
    numero VARCHAR(50),
    type ENUM('perso', 'pro'),
    foreign key (id_contact) references contacts(id)

);


insert into contacts(nom, sexe, date_de_naissance, adresse, cp, ville,pays, pays_iso_3) values
('John Doe', 'Homme', '1985-05-15', '123 Main St', '10001', 'New York','Etats-Unis', 'USA'),
('Alice Smith', 'Femme', '1990-03-22', '456 Park Lane', 'SW1A 1AA', 'London','Royaume_Uni', 'GBR'),
('Carlos Rodriguez', 'Homme', '1982-08-10', '789 Calle Principal', '28001', 'Madrid','Espagne', 'ESP'),
('Sophie Dupont', 'Femme', '1988-11-27', '101 Rue de la Republique', '75001', 'Paris','France', 'FRA'),
('Ahmed Ali', 'Homme', '1980-07-03', '456 Nile Street', '11511', 'Cairo','Egypte', 'EGY'),
('Maria Gonzalez', 'Femme', '1992-04-18', '789 Avenida de la Reforma', '06700', 'Mexico City','Mexique', 'MEX'),
('Yuki Tanaka', 'Femme', '1987-09-05', '123 Sakura Lane', '100-0001', 'Tokyo','Japon', 'JPN'),
('Ricardo Silva', 'Homme', '1984-01-30', '456 Avenida Paulista', '01310-100', 'São Paulo','Brazil', 'BRA'),
('Priya Patel', 'Femme', '1989-06-12', '789 Mumbai Street', '400001', 'Mumbai','Inde', 'IND'),
('Ivan Ivanov', 'Homme', '1983-12-08', '101 Red Square', '103073', 'Moscow','Russie', 'RUS');


insert into telephone (id_contact, numero, type) values
(1, '+93123456789', 'perso'),  
(4, '+551122334455', 'perso'), 
(2, '+15445566778', 'perso'),  
(3, '+811122233344', 'perso'), 
(2, '+33123456789', 'pro'),    
(1, '+441234567890', 'pro'),   
(3, '+813344556677', 'pro'),   
(5, '+861516171819', 'pro'),
(4, '+491234567890', 'pro'),   
(5, '+911011121314', 'perso');


describe contacts;
describe pays;
describe telephone;

select * from contacts ;
select * from pays;
select * from contacts left join telephone ON telephone.id_contact=contacts.id;


